apiVersion: apps/v1
kind: Deployment
metadata:
  name: listener-deployment
  labels:
    app: listener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: listener
  template:
    metadata:
      labels:
        app: listener
    spec:
      containers:
        - name: listener
          image: quay.io/tkrishtop/webapp:listener
          imagePullPolicy: Always
          ports:
            - containerPort: 3003
          env:
            - name: WINNIE_URL
              valueFrom:
                configMapKeyRef:
                  name: listener-config
                  key: winnie-url
            - name: PIGLET_URL
              valueFrom:
                configMapKeyRef:
                  name: listener-config
                  key: piglet-url
            - name: WINNIE_PORT
              valueFrom:
                configMapKeyRef:
                  name: listener-config
                  key: winnie-port
            - name: PIGLET_PORT
              valueFrom:
                configMapKeyRef:
                  name: listener-config
                  key: piglet-port
---
apiVersion: v1
kind: Service
metadata:
  name: listener-service
spec:
  type: NodePort
  selector:
    app: listener
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      nodePort: 30103
