apiVersion: v1
kind: ConfigMap
metadata:
  name: listener-config
data:
  config_file: "speakers-config.yaml"
  speakers-config.yaml: |
      - name: winnie
        url: winnie-service
        port: ":3000"
      - name: piglet
        url: piglet-service
        port: ":3002"
