apiVersion: apps/v1
kind: Deployment
metadata:
  name: winnie-deployment
  labels:
    app: speaker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speaker
  template:
    metadata:
      labels:
        app: speaker
    spec:
      containers:
      - name: winnie
        image: quay.io/tkrishtop/webapp:speaker
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: SPEAKER_NAME
          valueFrom:
            configMapKeyRef:
              name: speaker-config
              key: winnie-name
        - name: SPEAKER_PORT
          valueFrom:
            configMapKeyRef:
              name: speaker-config
              key: winnie-port
        - name: SPEAKER_SPEECH
          valueFrom:
            configMapKeyRef:
              name: speaker-config
              key: winnie-speech
---
apiVersion: v1
kind: Service
metadata:
  name: winnie-service
spec:
  type: NodePort
  selector:
    app: speaker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
