apiVersion: apps/v1
kind: Deployment
metadata:
  name: speaker-deployment
  labels:
    app: speaker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: speaker
  template:
    metadata:
      labels:
        app: speaker
    spec:
      containers:
      - name: speaker
        image: quay.io/tkrishtop/webapp:speaker
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: speaker-service
spec:
  type: NodePort
  selector:
    app: speaker
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30100
